import "./globals.css";
//  Next
import { Poppins } from "next/font/google";
import type { Metadata } from "next";
import dynamic from "next/dynamic";
// Components
const Header = dynamic(() => import("@/app/components/Header"));

// Font
const poppinsFont = Poppins({
  subsets: ["latin", "latin-ext"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Agency portfolio website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppinsFont.className} style={{ minHeight: "200vh" }}>
        <Header />
        {children}
      </body>
    </html>
  );
}
